config/routes.rb
Rails.application.routes.draw do
  resources :articles

  resources :tags

  # You can have the root of your site routed with "root"
  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  #has_many :tag_article_assocs
  #has_many :tags, through: :tag_article_assocs
  has_and_belongs_to_many :tags
  validates :title, presence: true, length: { minimum: 5 }, uniqueness: true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  #has_many :tag_article_assocs
  #has_many :articles, through: :tag_article_assocs
  has_and_belongs_to_many :articles
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new

    @tags = Tag.all

    @article_tags = @article.tags.build
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    @tag = Tag.where(:id => params[:taging_article])

    @article.tags << @tag

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    @tag = Tag.where(:id => params[:taging_article])

    @article.tags.destroy_all

    @article.tags << @tag

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def new
    @tag = Tag.new
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to tags_path
    else
      render 'new'
    end
  end

  def update
    @tag = Tag.find(params[:id])

    if @tag.update(tag_params)
      redirect_to tags_path
    else
      render 'edit'
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    redirect_to tags_path
  end

  private
  def tag_params
    params.require(:tag).permit(:name)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.label :tags %><br>

    <%= select_tag "taging_article",
     options_from_collection_for_select(Tag.all, 'id', 'name',
     @article.tags.map{ |a| a.id }), :multiple => true %>
  </p>


  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<head>
<style>
ol, ul {
    list-style: none;
}
li.grid {
  font: 13px "Helvetica Neue", Helvetica, Arial, sans-serif;
    float: left;
    width: 320px;
    height: 360px;
    padding: 10px;
    border: 5px solid gray;
    margin: 10px;
}

li.grid h2 {
  font-weight: bold;
  font-size: 20px;
    margin-bottom: 2px;
    max-width: 300px;
    overflow: hidden;
}

li.grid h3 {
  font-size: 11px;
  margin-top: 2px;
  color: #999;
  float: left;
  margin-right: 5px;
}

li.grid p {
    margin: 10px 15px;
    height: 265px;
    max-height: 240px;
    width: 300px;
    max-width: 300px;
    overflow: hidden;
}

.floating-box {
    float: left;
    max-width: 300px;
    margin: 0px 7px;
  }

</style>
</head>


<h1>Listing Articles</h1>
<div>
  <%= link_to 'New article', new_article_path %> | <%= link_to 'Go to Tags', tags_path %>
  <ol>

    <% @articles.each do |article| %>
      <li class="grid">
        <h2><%= article.title %></h2>
        <% article.tags.each do |tag| %>
          <h3><%= tag.name %></h3>
        <% end %>
        <p><%= article.text %></p>
        <ol>
          <li class="floating-box"><%= link_to 'Show', article_path(article) %></li>
          <li class="floating-box"><%= link_to 'Edit', edit_article_path(article) %></li>
          <li class="floating-box"><%= link_to 'Destroy', article_path(article),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %></li>
        </ol>
      </li>
    <% end %>
  </ol>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @article.tags.map{ |tag| tag.name}.join(",") %>
</p>
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= form_for :tag, url: tag_path(@tag), method: :patch do |f| %>

  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@tag.errors.count, "error") %> prohibited
        this tag from being saved:
      </h2>
      <ul>
        <% @tag.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing Tags</h1>

<%= link_to 'New tag', new_tag_path %> | <%= link_to 'Go to articles', articles_path %>

<table>
  <tr>
    <th>Name</th>
    <th colspan="2"></th>
  </tr>

  <% @tags.each do |tag| %>
    <tr>
      <td><%= tag.name %></td>
      <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
      <td><%= link_to 'Destroy', tag_path(tag),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<% if @tag.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@tag.errors.count, "error") %> prohibited
      this tag from being saved:
    </h2>
    <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for :tag, url: tags_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', tags_path %>

app/views/welcome/index.html.erb
<h1>Hello, eProductions!</h1>
<%= link_to 'My Blog', controller: 'articles' %>